name: La Persé
favicon: null
layout_spectrum: 0.09611
typography_spectrum: 0.6747
title: LA PERSÉ - THE MOST TALKED ABOUT CLUB NIGHT IN HELSINKI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaf3fc'
    - '#548c9d'
    - '#a9b4c8'
    - '#002454'
    - '#2f606e'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
