name: La Persé
favicon: null
layout_spectrum: 0.50435
typography_spectrum: 0.18387
title: LA PERSÉ - THE MOST TALKED ABOUT CLUB NIGHT IN HELSINKI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff15c'
    - '#1f1e1d'
    - '#eaf3fc'
    - '#5c592e'
    - '#c2b84a'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
