name: La Persé
favicon: null
layout_spectrum: 0.49671
typography_spectrum: 0.34174
title: CLUB LA PERSÉ
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c3c4e'
    - '#507a91'
    - '#3b657c'
    - '#20485f'
    - '#285475'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
