name: La Persé
favicon: null
layout_spectrum: 0.52768
typography_spectrum: 0.22931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e30038'
    - '#2c1868'
    - '#48185f'
    - '#721653'
    - '#9d1147'
  brandStrength: 0.9375
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
