name: La Persé
favicon: null
layout_spectrum: 0.8047534422948956
typography_spectrum: 0.7079930589534342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3271374988835305
  lightness: 0.4060048598330468
  saturation: 0.10053205979056656
  rhythmicContrast: 0.5756926275789738
purpose: []
